#ifndef ML_KEM_CONFIG_H
#define ML_KEM_CONFIG_H

#define MLKEM_Q 3329
#define MLKEM_N  256
#define K 4
#define MLKEM_ETA 2
#define D_U 11
#define D_U_ENCODING_LEN 32*D_U
#define D_UPSILON 5
#define KEY_SEED_LEN 33
#define ENCODING_LEN 12
#define POLY_BYTE_LEN (ENCODING_LEN*MLKEM_N)/8
#define CBD_SEED_LEN 64*MLKEM_ETA
#define C_1_LEN 32*D_U*K
#define C_2_LEN 32*D_UPSILON
#define PKE_SEED_KEN 64
#define PKE_PUB_KEY_LEN 384*K + 32
#define PKE_PRV_KEY_LEN 384*K
#define PKE_CIPHERTEX_LEN 32*(D_U*K + D_UPSILON)
#define SECRET_LEN 32
#define KEY_HASH_LEN 32
#define ENCAPS_HASH_LEN 64
#define RANDOM_LEN 32
#define KEM_DECAP_LEN (PKE_PRV_KEY_LEN + PKE_PUB_KEY_LEN + KEY_HASH_LEN + RANDOM_LEN)
#define KEY_HASH_OFFSET (PKE_PRV_KEY_LEN + PKE_PUB_KEY_LEN)
#define Z_OFFSET (KEY_HASH_OFFSET + RANDOM_LEN)
#define RANDOM_GEN_ERROR -1
#define KEY_SIZE_ERROR -2
#define MALFORMED_KEY_ERROR -3
#define CIPHERTEXT_SIZE_ERROR -4

#endif
